---
name: tests
on:
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  unit-tests:
    strategy:
      matrix:
        go-version: ['1.19', '1.20', '1.21', 'oldstable', 'stable']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./...
